function export_equivalence_fixture(output_path)
%EXPORT_EQUIVALENCE_FIXTURE Export a deterministic short FedMCANC trace.
%
% Run from any directory with MATLAB and the repository available:
%
%   export_equivalence_fixture("matlab_equivalence.mat")
%
% Then validate it from "Python version":
%
%   set IC_DMCANC_MATLAB_FIXTURE=matlab_equivalence.mat
%   python -m unittest tests.test_matlab_equivalence -v
%
% This helper does not modify the authoritative MATLAB implementation.

if nargin < 1
    output_path = fullfile(pwd, "matlab_equivalence.mat");
end

helper_dir = fileparts(mfilename("fullpath"));
python_dir = fileparts(helper_dir);
repository_root = fileparts(python_dir);
addpath(repository_root);

rng(17, "twister");

num_nodes = 6;
num_samples = 8;
w_len = 3;
s_len = 3;
c_len = 2;
mu_w = 0.01;
alpha = 0.2;

reference = 0.2 * randn(1, num_samples);
disturbance = 0.1 * randn(num_nodes, num_samples);
secondary_path = 0.03 * randn(num_nodes, num_nodes, s_len);
for node_index = 1:num_nodes
    secondary_path(node_index, node_index, 1) = ...
        secondary_path(node_index, node_index, 1) + 0.3;
end

compensation_filters = 0.02 * randn(num_nodes, num_nodes, c_len);
for node_index = 1:num_nodes
    compensation_filters(node_index, node_index, :) = 0;
end

initial_center = 0.01 * randn(num_nodes, w_len + c_len - 1);
controller = FedMCANC( ...
    w_len, ...
    secondary_path, ...
    s_len, ...
    num_nodes, ...
    num_samples, ...
    disturbance, ...
    reference, ...
    c_len, ...
    initial_center);
controller.C = compensation_filters;

[residual_error, controller] = FedMCANC_166_ideal( ...
    controller, mu_w, alpha, initial_center);

control_output = controller.yc;
final_local_weights = controller.Wc;
final_center_weights = controller.Wcsubopt;
final_weight_difference = controller.Nabla;

save( ...
    output_path, ...
    "reference", ...
    "disturbance", ...
    "secondary_path", ...
    "compensation_filters", ...
    "initial_center", ...
    "w_len", ...
    "s_len", ...
    "c_len", ...
    "mu_w", ...
    "alpha", ...
    "residual_error", ...
    "control_output", ...
    "final_local_weights", ...
    "final_center_weights", ...
    "final_weight_difference", ...
    "-v7");

fprintf("Saved MATLAB/Python equivalence fixture: %s\n", output_path);
end
